version: "3"
name: bia-eb
services:
  server:
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: User ID=postgres;Password=emYiSFGDjoXMoVhfp4Cy;Server=bia.cxq8wks8qvdp.us-east-1.rds.amazonaws.com;Port=5432;Database=bia; Pooling=true;
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    image: 211125447912.dkr.ecr.us-east-1.amazonaws.com/bia:5e1a71c
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: bia-eb_default
