name: bia-eb
services:
  server:
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: User ID=postgres;Password=fnRUuqkdGC0KvUJozq6u;Server=bia.cxq8wks8qvdp.us-east-1.rds.amazonaws.com;Port=5432;Database=bia; Pooling=true;
      DB_HOST: bia.cxq8wks8qvdp.us-east-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_PWD: fnRUuqkdGC0KvUJozq6u
      DB_USER: postgres
    image: 211125447912.dkr.ecr.us-east-1.amazonaws.com/bia:5ee3210
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: bia-eb_default
